# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env && cargo install mdbook --version 0.4.40
    - source $HOME/.cargo/env && cd docs && mdbook build --dest-dir $READTHEDOCS_OUTPUT/html
