# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # Download pre-built mdbook binary
    - mkdir -p $HOME/.local/bin
    - curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C $HOME/.local/bin
    - $HOME/.local/bin/mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html
